project:
  type: website
  output-dir: docs
  
website:
  title: "TEST WEBSITE"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/RahulSamaddar1982/Mytestwebsite
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Rahul Samaddar"

format:
  html:
    theme: cerulean
    toc: true

editor: source

